#:schema node_modules/wrangler/config-schema.json
name = "joehouse"
main = "src/index.js"
compatibility_date = "2024-01-01"
# account_id = "YOUR_ACCOUNT_ID" # 선택 사항이며, wrangler login을 사용하는 경우 필요하지 않을 수 있습니다.
workers_dev = true
